# Generated by Django 4.0.4 on 2023-11-22 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='MLmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ml_file', models.FileField(upload_to='ml_model')),
            ],
        ),
        migrations.CreateModel(
            name='Pat_file',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pat_seq', models.FileField(upload_to='pat_file')),
            ],
        ),
        migrations.CreateModel(
            name='Pro_file',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_seq', models.FileField(upload_to='pro_file')),
            ],
        ),
        migrations.CreateModel(
            name='Seq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.FileField(upload_to='seq')),
            ],
        ),
    ]
